### ISSUE TITLE
AWSGuard vNext

### ISSUE THREAD

**Issue by t0yv0** [pulumi/pulumi-policy-aws#111]
```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-policy-aws/issues/110
- [ ] https://github.com/pulumi/pulumi-policy-aws/issues/104
- [ ] https://github.com/pulumi/pulumi-policy-aws/issues/88
- [ ] https://github.com/pulumi/pulumi-policy-aws/issues/36
- [ ] https://github.com/pulumi/pulumi-policy-aws/pull/107
- [ ] https://github.com/pulumi/pulumi-policy-aws/pull/108
- [ ] https://github.com/pulumi/pulumi-policy-aws/pull/103
- [ ] https://github.com/pulumi/pulumi-policy-aws/pull/93
- [ ] Get friction log from Cloud team
```
